[project]
name = "rwr"
version = "0.1.0"
description = "Random Walk with Restarts"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "networkx>=3.5",
    "numpy>=2.3.0",
    "scipy>=1.15.3",
]
